# Generated by Django 4.2.4 on 2023-08-10 14:47

from django.db import migrations, models
import jwt_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_remove_user_identifier_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', jwt_auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
